version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:41"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:47"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
